# frozen_string_literal: true

source "https://rubygems.org"

# The SDK from this repository, not a published version.
gem "docuconf-anyway", path: "../.."

gem "rack", "~> 3.1"
gem "rackup", "~> 2.2"
gem "webrick", "~> 1.9"

group :test do
  gem "minitest", ">= 5.20"
end
