# frozen_string_literal: true

RSpec.describe "contract export" do
  GOLDEN = File.expand_path("golden/gateway.cue", __dir__)
  FIXTURES = File.expand_path("fixtures", __dir__)

  def export_gateway(**opts)
    Docuconf::Anyway.export(name: "sample-gateway", classes: [Fixtures::GatewayConfig], root: FIXTURES, **opts)
  end

  def anon(name, &block)
    Class.new(Anyway::Config) do
      include Docuconf::Anyway
      config_name name
      class_eval(&block)
    end
  end

  it "matches the golden file (every var type and every file type)" do
    text = export_gateway
    if ENV["UPDATE_GOLDEN"] == "1"
      File.write(GOLDEN, text)
    end
    expect(text).to eq File.read(GOLDEN)
  end

  it "is deterministic, with vars and files sorted by name" do
    text = export_gateway
    expect(export_gateway).to eq text
    data = Docuconf::Anyway::Exporter.new(name: "sample-gateway", classes: [Fixtures::GatewayConfig], root: FIXTURES).contract
    expect(data["vars"].keys).to eq data["vars"].keys.sort
    expect(data["files"].keys).to eq data["files"].keys.sort
    expect(text).to start_with("// Code generated by docuconf. DO NOT EDIT.\npackage sample_gateway\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & {")
  end

  it "passes cue vet -c against the meta-schema" do
    require_cue!
    ok, out = cue_vet(export_gateway)
    expect(ok).to be(true), out
  end

  it "exports length limits that pass cue vet -c" do
    require_cue!
    klass = anon(:lens) do
      attr_config callback: "https://a.example/run", limits: nil, branches: %w[ZÜ01 BE]
      coerce_types callback: :uri, limits: :json, branches: {type: :string, array: true}
      describe :callback, "Where to report each run", schemes: %w[https], max_length: 24
      describe :limits, "Run limits as a JSON object", max_length: 16
      describe :branches, "Branch codes, two to four characters each", item_min_length: 2, item_max_length: 4
    end
    text = Docuconf::Anyway.export(name: "lens", classes: [klass])
    expect(text).to match(/maxLength:\s+24/).and match(/maxLength:\s+16/)
      .and match(/itemMinLength:\s+2/).and match(/itemMaxLength:\s+4/)
    ok, out = cue_vet(text)
    expect(ok).to be(true), out
  end

  it "exports YAML values: deployable environment sections as profiles selected by RAILS_ENV" do
    exporter = Docuconf::Anyway::Exporter.new(name: "gw", classes: [Fixtures::GatewayConfig], root: FIXTURES)
    data = exporter.contract
    expect(data["profiles"]).to eq(
      "selector" => "RAILS_ENV",
      "default" => "development",
      "defaults" => {
        "production" => {"GATEWAY_LOG_LEVEL" => "warn", "GATEWAY_REQUEST_TIMEOUT" => "10s"},
        "staging" => {"GATEWAY_LOG_LEVEL" => "debug", "GATEWAY_SAMPLE_RATE" => 1.0}
      }
    )
    expect(data["vars"]["RAILS_ENV"]).to include("type" => "string", "default" => "development")
    expect(exporter.warnings).to include(
      "ignoring the development section of config/gateway.yml (not deployable profiles)",
      a_string_including("RAILS_ENV defaults to development, which has no exported profile")
    )
  end

  it "exports the profiles asked for, and the default profile given" do
    data = Docuconf::Anyway::Exporter.new(name: "gw", classes: [Fixtures::GatewayConfig], root: FIXTURES,
      export_profiles: %w[development production], default_profile: "production").contract
    expect(data["profiles"]["defaults"].keys).to eq %w[development production]
    expect(data["profiles"]["default"]).to eq "production"
    expect(data["vars"]["RAILS_ENV"]["default"]).to eq "production"
  end

  it "accepts a dev/test secret in YAML, since those sections are not exported" do
    Dir.mktmpdir do |root|
      write_file(root, "config/orders.yml",
        "development:\n  database_url: postgres://localhost/dev\ntest:\n  database_url: postgres://localhost/test\n" \
        "production:\n  port: 443\n")
      klass = anon(:orders) do
        attr_config :database_url, port: 8080
        required :database_url
        describe :database_url, "Postgres connection string", type: :url, secret: true
        describe :port, "HTTP listen port"
      end
      data = Docuconf::Anyway::Exporter.new(name: "orders", classes: [klass], root: root).contract
      expect(data["profiles"]["defaults"]).to eq("production" => {"ORDERS_PORT" => 443})
      expect(data["vars"]["ORDERS_DATABASE_URL"]).to include("required" => true, "secret" => true)

      expect { Docuconf::Anyway::Exporter.new(name: "orders", classes: [klass], root: root, export_profiles: %w[development]).contract }
        .to raise_error(Docuconf::Anyway::DeclarationError, /must not have a value in the development section/)
    end
  end

  it "exports the same contract whatever the current environment, honouring required env:" do
    klass = nil
    contracts = %w[development test production].map do |env|
      allow(Anyway::Settings).to receive(:current_environment).and_return(env)
      klass = anon(:envreq) do
        attr_config :database_url, :sentry_dsn, :debug_token
        required :database_url, env: "production"
        required :sentry_dsn, env: %w[staging production]
        required :debug_token, env: :development
        describe :database_url, "Postgres connection string"
        describe :sentry_dsn, "Sentry DSN for errors"
        describe :debug_token, "Token for the debug bar"
      end
      Docuconf::Anyway::Exporter.new(name: "envreq", classes: [klass]).to_cue
    end
    expect(contracts.uniq.size).to eq 1
    vars = Docuconf::Anyway::Exporter.new(name: "envreq", classes: [klass]).contract["vars"]
    expect(vars["ENVREQ_DATABASE_URL"]["required"]).to be true
    expect(vars["ENVREQ_SENTRY_DSN"]["required"]).to be true
    expect(vars["ENVREQ_DEBUG_TOKEN"]).not_to have_key("required")
  end

  it "fails when no config class is found, unless allow_empty" do
    expect { Docuconf::Anyway::Exporter.new(name: "x", classes: []).contract }
      .to raise_error(Docuconf::Anyway::DeclarationError, /no config classes found/)
    expect(Docuconf::Anyway::Exporter.new(name: "x", classes: [], allow_empty: true).contract["vars"]).to eq({})
  end

  it "exports values of a non-environmental YAML file as defaults, making required ones optional" do
    Dir.mktmpdir do |root|
      write_file(root, "config/plain.yml", "host: db.internal\nport: 5433\n")
      klass = anon(:plain) do
        attr_config :host, port: 5432
        required :host
        describe :host, "Database host"
        describe :port, "Database port"
      end
      data = Docuconf::Anyway::Exporter.new(name: "plain", classes: [klass], root: root).contract
      expect(data["vars"]["PLAIN_HOST"]).to include("default" => "db.internal")
      expect(data["vars"]["PLAIN_HOST"]).not_to have_key("required")
      expect(data["vars"]["PLAIN_PORT"]["default"]).to eq 5433
      expect(data).not_to have_key("profiles")
    end
  end

  it "rejects a secret with a value in a YAML file, and a profile value that breaks a constraint" do
    Dir.mktmpdir do |root|
      write_file(root, "config/bad.yml", "production:\n  token: abc\n  port: 70000\n")
      klass = anon(:bad) do
        attr_config :token, port: 80
        describe :token, "API token"
        secret :token
        describe :port, "Listen port", max: 65_535
      end
      expect { Docuconf::Anyway.export(name: "bad", classes: [klass], root: root) }
        .to raise_error(Docuconf::Anyway::DeclarationError) { |e|
          expect(e.problems).to contain_exactly(
            "BAD_TOKEN: a secret must not have a value in the production section of config/bad.yml; it would ship in the image",
            "BAD_PORT: config/bad.yml (production): 70000 is above max 65535"
          )
        }
    end
  end

  it "leaves excluded (credentials-only) attributes out" do
    data = Docuconf::Anyway::Exporter.new(name: "gw", classes: [Fixtures::GatewayConfig], root: FIXTURES).contract
    expect(data["vars"]).not_to have_key("GATEWAY_SECRET_KEY_BASE")
  end

  it "merges several config classes and rejects duplicate names" do
    a = anon(:alpha) { attr_config port: 1; describe :port, "Alpha port" }
    b = anon(:beta) { attr_config port: 2; describe :port, "Beta port" }
    data = Docuconf::Anyway::Exporter.new(name: "two", classes: [a, b], profiles: false).contract
    expect(data["vars"].keys).to eq %w[ALPHA_PORT BETA_PORT]

    c = anon(:alpha2) { env_prefix "ALPHA"; attr_config port: 3; describe :port, "Another port" }
    expect { Docuconf::Anyway.export(name: "dup", classes: [a, c], profiles: false) }
      .to raise_error(Docuconf::Anyway::DeclarationError, /ALPHA_PORT is declared by both/)
  end

  it "rejects a service name that is not a DNS label" do
    expect { Docuconf::Anyway.export(name: "Bad_Name", classes: [Fixtures::GatewayConfig], profiles: false) }
      .to raise_error(Docuconf::Anyway::DeclarationError, /must be a DNS label/)
  end

  it "does not need a valid environment" do
    without_prefix("GATEWAY_") do
      expect { export_gateway }.not_to raise_error
    end
  end

  describe "docuconf CLI" do
    it "exports from a Ruby file" do
      Dir.mktmpdir do |dir|
        out = File.join(dir, "contract.cue")
        err = StringIO.new
        code = Docuconf::Anyway::CLI.start(
          ["export", "-n", "sample-gateway", "--root", FIXTURES, "-c", "Fixtures::GatewayConfig", "-o", out,
            File.expand_path("fixtures/gateway_config.rb", __dir__)], out: StringIO.new, err: err
        )
        expect(code).to eq 0
        expect(File.read(out)).to eq File.read(GOLDEN)
      ensure
        Docuconf::Anyway.export_mode = false
      end
    end

    it "fails when the files define no config class, unless --allow-empty" do
      exe = File.expand_path("../exe/docuconf", __dir__)
      lib = File.expand_path("../lib", __dir__)
      out, status = Open3.capture2e(RbConfig.ruby, "-I", lib, exe, "export", "-n", "x")
      expect(status.exitstatus).to eq 1
      expect(out).to include("no config classes found").and include("config/configs/*.rb")

      out, status = Open3.capture2e(RbConfig.ruby, "-I", lib, exe, "export", "-n", "x", "--allow-empty")
      expect(status).to be_success, out
      expect(out).to include("vars: {}")
    end

    it "--check exits 1 when the contract file is out of date, and writes nothing" do
      Dir.mktmpdir do |dir|
        out = File.join(dir, "contract.cue")
        args = ["export", "-n", "sample-gateway", "--root", FIXTURES, "-c", "Fixtures::GatewayConfig", "-o", out, "--check",
          File.expand_path("fixtures/gateway_config.rb", __dir__)]
        err = StringIO.new
        expect(Docuconf::Anyway::CLI.start(args, out: StringIO.new, err: err)).to eq 1
        expect(err.string).to include("#{out} is missing")
        expect(File.exist?(out)).to be false

        File.write(out, File.read(GOLDEN))
        err = StringIO.new
        expect(Docuconf::Anyway::CLI.start(args, out: StringIO.new, err: err)).to eq 0
        expect(err.string).to include("is up to date")

        # Another gem version alone is not drift.
        File.write(out, File.read(GOLDEN).sub(/(generator: \{[^}]*version: +)"[^"]*"/m, '\1"9.9.9"'))
        expect(File.read(out)).to include('"9.9.9"')
        expect(Docuconf::Anyway::CLI.start(args, out: StringIO.new, err: StringIO.new)).to eq 0

        File.write(out, File.read(GOLDEN).sub("8080", "8081"))
        expect(Docuconf::Anyway::CLI.start(args, out: StringIO.new, err: StringIO.new)).to eq 1
      ensure
        Docuconf::Anyway.export_mode = false
      end
    end

    it "names a missing file instead of printing a backtrace" do
      err = StringIO.new
      expect(Docuconf::Anyway::CLI.start(["export", "-n", "x", "config/nope.rb"], out: StringIO.new, err: err)).to eq 2
      expect(err.string).to eq "docuconf: invalid argument: config/nope.rb: no such file\n"
    ensure
      Docuconf::Anyway.export_mode = false
    end

    it "fails without --name" do
      err = StringIO.new
      expect(Docuconf::Anyway::CLI.start(["export"], out: StringIO.new, err: err)).to eq 2
      expect(err.string).to include("missing argument: --name")
    end

    it "runs as an executable" do
      Dir.mktmpdir do |dir|
        file = File.join(dir, "app_config.rb")
        File.write(file, <<~RUBY)
          class AppConfig < Anyway::Config
            include Docuconf::Anyway
            attr_config port: 8080
            describe :port, "HTTP listen port", min: 1, max: 65535
          end
        RUBY
        exe = File.expand_path("../exe/docuconf", __dir__)
        lib = File.expand_path("../lib", __dir__)
        out, status = Open3.capture2e(RbConfig.ruby, "-I", lib, exe, "export", "-n", "app", file, chdir: dir)
        expect(status).to be_success, out
        expect(out).to include("APP_PORT: {")

        out, status = Open3.capture2e({"APP_PORT" => "0"}, RbConfig.ruby, "-I", lib, exe, "check", file, chdir: dir)
        expect(status.exitstatus).to eq(1), out
        expect(out).to include("APP_PORT [out_of_range]: 0 is below min 1")
      end
    end
  end
end
