# frozen_string_literal: true

require "json"

module Docuconf
  module Anyway
    # A small CUE writer for plain data (SPEC §4: contracts are data). The
    # output follows `cue fmt`: tabs, aligned runs of scalar fields, lists of
    # scalars inline.
    module CUE
      IDENT = /\A[A-Za-z][A-Za-z0-9_]*\z/
      KEYWORDS = %w[package import for in if let true false null _ __ div mod quo rem].freeze

      module_function

      def label(key)
        k = key.to_s
        IDENT.match?(k) && !KEYWORDS.include?(k) ? k : JSON.generate(k)
      end

      def scalar?(v) = !(v.is_a?(Hash) || v.is_a?(Array))

      def scalar(v)
        case v
        when String then JSON.generate(v)
        when Symbol then JSON.generate(v.to_s)
        when Integer then v.to_s
        when Float
          raise ArgumentError, "cannot write #{v} in CUE" unless v.finite?

          v == v.floor && v.abs < 1e15 ? v.to_i.to_s : JSON.generate(v)
        when Rational then scalar(v.to_f)
        when true, false then v.to_s
        when nil then "null"
        else raise ArgumentError, "cannot write #{v.class} in CUE"
        end
      end

      def value(v, indent)
        return scalar(v) if scalar?(v)

        if v.is_a?(Array)
          return "[]" if v.empty?
          return "[#{v.map { |x| scalar(x) }.join(", ")}]" if v.all? { |x| scalar?(x) }

          inner = "#{indent}\t"
          return "[\n#{v.map { |x| "#{inner}#{value(x, inner)}," }.join("\n")}\n#{indent}]"
        end
        return "{}" if v.empty?

        "{\n#{fields(v, "#{indent}\t")}\n#{indent}}"
      end

      def fields(hash, indent)
        lines = []
        run = []
        flush = lambda do
          width = run.map { |l, _| l.length }.max
          run.each { |l, val| lines << "#{indent}#{l}:#{" " * (width - l.length + 1)}#{val}" }
          run = []
        end
        hash.each do |k, v|
          l = label(k)
          if scalar?(v)
            run << [l, scalar(v)]
          else
            flush.call unless run.empty?
            lines << "#{indent}#{l}: #{value(v, indent)}"
          end
        end
        flush.call unless run.empty?
        lines.join("\n")
      end

      # The whole contract file.
      def document(contract, package:)
        <<~CUE
          // Code generated by docuconf. DO NOT EDIT.
          package #{package}

          import "docuconf.dev/contract"

          contract.#Contract & #{value(contract, "")}
        CUE
      end
    end
  end
end
