// Code generated by docuconf. DO NOT EDIT.
package sample_gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "sample-gateway"
		generator: {
			language: "ruby"
			sdk:      "docuconf-anyway"
			version:  "0.1.0"
		}
	}
	vars: {
		GATEWAY_ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			required:    true
			configKey:   "gateway.allowed_origins"
			items:       "string"
			encoding:    "csv"
			separator:   ","
			minItems:    1
			maxItems:    10
		}
		GATEWAY_DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			configKey:   "gateway.database_url"
			schemes: ["postgres", "postgresql"]
		}
		GATEWAY_DEBUG: {
			type:        "bool"
			description: "Verbose request logging"
			configKey:   "gateway.debug"
			default:     false
		}
		GATEWAY_GOMEMLIMIT: {
			type:        "int"
			description: "Soft memory limit, in bytes"
			configKey:   "gateway.gomemlimit"
			min:         1
		}
		GATEWAY_KEYSTORE_PASSWORD: {
			type:        "string"
			description: "Password for the partner keystore"
			secret:      true
			configKey:   "gateway.keystore_password"
			minLength:   1
		}
		GATEWAY_LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			group:       "logging"
			configKey:   "gateway.log_level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		GATEWAY_PORT: {
			type:        "int"
			description: "HTTP listen port"
			configKey:   "gateway.port"
			min:         1
			max:         65535
			default:     8080
		}
		GATEWAY_PUBLIC_URL: {
			type:        "url"
			description: "Externally visible base URL"
			required:    true
			configKey:   "gateway.public_url"
			schemes: ["https"]
		}
		GATEWAY_RATE_LIMITS: {
			type:        "json"
			description: "Default per-client rate limits"
			configKey:   "gateway.rate_limits"
			schema: {
				type: "object"
				properties: {
					perMinute: {
						type:    "integer"
						minimum: 1
					}
					burst: {
						type:    "integer"
						minimum: 0
					}
				}
				required: ["perMinute"]
				additionalProperties: false
			}
		}
		GATEWAY_REGION: {
			type:        "string"
			description: "Cloud region the service runs in"
			required:    true
			configKey:   "gateway.region"
			examples: ["eu-west-1"]
			minLength: 4
			maxLength: 32
			pattern:   "^[a-z]{2}-[a-z]+-[0-9]$"
		}
		GATEWAY_REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Upstream request timeout"
			configKey:   "gateway.request_timeout"
			encoding:    "iso8601"
			min:         "1s"
			max:         "5m"
			default:     "30s"
		}
		GATEWAY_SAMPLE_RATE: {
			type:        "float"
			description: "Fraction of requests traced"
			configKey:   "gateway.sample_rate"
			min:         0
			max:         1
			default:     0.25
		}
		GATEWAY_WORKER_PORTS: {
			type:        "list"
			description: "Ports the workers bind"
			configKey:   "gateway.worker_ports"
			items:       "int"
			encoding:    "csv"
			separator:   ","
			itemMin:     1
			itemMax:     65535
		}
		RAILS_ENV: {
			type:        "string"
			description: "Environment the app runs in; selects the matching section of its config/*.yml files"
			default:     "development"
		}
	}
	files: {
		geoip: {
			type:        "binary"
			description: "GeoIP database for country-based routing"
			path:        "/data/geoip/GeoLite2-City.mmdb"
			maxSize:     134217728
		}
		license: {
			type:        "text"
			description: "Gateway licence key"
			required:    true
			path:        "/etc/gateway/license/license.key"
			pattern:     "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		"partner-keystore": {
			type:        "keystore"
			format:      "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			secret:      true
			path:        "/etc/gateway/partner/keystore.p12"
			passwordVar: "GATEWAY_KEYSTORE_PASSWORD"
		}
		routes: {
			type:        "config"
			format:      "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required:    true
			path:        "/etc/gateway/routes/routes.yaml"
			pathEnv:     "ROUTES_FILE"
			reload:      "watch"
			maxSize:     65536
			schema: {
				type: "object"
				properties: {
					routes: {
						type: "array"
						items: {
							type: "object"
							properties: {
								match: {
									type:    "string"
									pattern: "^/"
								}
								upstream: {
									type:    "string"
									pattern: "^https?://"
								}
								timeout: {
									type: "string"
								}
							}
							required: ["match", "upstream"]
							additionalProperties: false
						}
						minItems: 1
					}
				}
				required: ["routes"]
				additionalProperties: false
			}
		}
		"serving-tls": {
			type:        "tls"
			description: "Certificate the gateway serves HTTPS with"
			required:    true
			secret:      true
			path:        "/etc/gateway/tls"
			reload:      "watch"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
			requireCA:    true
		}
		"upstream-ca": {
			type:        "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path:        "/etc/gateway/ca/bundle.pem"
			pathEnv:     "SSL_CERT_FILE"
		}
	}
	overlays: {
		platform: {
			format:       "yaml"
			description:  "Settings the platform supplies as a mounted file"
			path:         "/etc/gateway/overlay/gateway.yml"
			keySeparator: "."
			reload:       "watch"
		}
	}
	profiles: {
		selector: "RAILS_ENV"
		default:  "development"
		defaults: {
			production: {
				GATEWAY_LOG_LEVEL:       "warn"
				GATEWAY_REQUEST_TIMEOUT: "10s"
			}
			staging: {
				GATEWAY_LOG_LEVEL:   "debug"
				GATEWAY_SAMPLE_RATE: 1
			}
		}
	}
}
